title: Nighthawk Pages 
description: "Class of 2025"
owner_name: Soumini Kandula
github_username: Soumini97
github_repo: "soumini_2025" 
baseurl: "/soumini_2025"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/soumini_2025"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 
# remote_theme: pages-themes/midnight@v0.2.0
remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pagesthemes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/setup.md
  - navigation/calculator.md
  - navigation/cookie.md
  - navigation/guessnumber.md
  - navigation/snake.md 
  - navigation/sprint5.md



